version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: 'shayan'
    # ports:
    #   - 5432:5432
  express:
    build:
      context: ./backend
    environment: 
      - user=postgres
      - host=postgres
      - database=postgres
      - password=shayan
      # - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    # volumes: 
    #   - /app/node_modules
    #   - ./backend:/app
  angular:
    build:
      context: ./client
    ports: 
      - 80:80

      